return {
  {
    "nvim-treesitter/nvim-treesitter",
    opts = {
      ensure_installed = {
        "vim",
        "vimdoc",
        "lua",
        "html",
        "css",
        "javascript",
        "typescript",
        "tsx",
        "json",
        "go",
        "git_config",
        "toml",
        "gitignore",
        "gitcommit",
        "gomod",
        "gosum",
        "gowork",
        "hcl",
        "markdown",
        "python",
        "ruby",
        "terraform",
        "csv",
        "xml",
        "yaml",
        "graphql",
      },
    },
  },
  {
    "nvim-treesitter/nvim-treesitter-context",
    dependencies = "nvim-treesitter/nvim-treesitter",
    ft = { "go", "lua", "python", "javascript", "typescript", "rust", "cpp", "c", "java" },
  },
}
