return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "vim",
      "vimdoc",
      "lua",
      "html",
      "css",
      "javascript",
      "typescript",
      "tsx",
      "json",
      "go",
      "git_config",
      "toml",
      "gitignore",
      "gitcommit",
      "gomod",
      "gosum",
      "gowork",
      "hcl",
      "markdown",
      "python",
      "ruby",
      "terraform",
      "csv",
      "xml",
      "yaml",
      "graphql",
    },
  },
}
